### ISSUE TITLE
Pie chart not showing

### ISSUE THREAD

**Issue by LeePower** [ekojsalim/votenexus#1]
Hi, thanks for the great voting app, however, the result pie chart is not showing, would you give some heads up on how to fix this problem? Thanks!

**Comment by ekojsalim** [comment]
I have pushed the fix for it, 26b299433ce9de7d8dbd8abebb5462a72c33d25e, the problem is with the highcharts.3d.js version, downgrading it worked as this project is old and outdated.

**Comment by LeePower** [comment]
Thanks it's working now!
